handlebars:
  suffix: .html

server:
  compression:
    enabled: true
#    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/json, application/javascript
    min-response-size: 10

  tomcat:
    accept-count: 1
    max-connections: 1
    threads:
      min-spare: 2
      max: 2
